// Code generated by protoc-gen-go.
// source: wire.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	wire.proto

It has these top-level messages:
	Login
	Contact
	Text
	File
	Av
	Store
	Load
	Haber
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Identifies which field is filled in
type Haber_Which int32

const (
	Haber_LOGIN      Haber_Which = 0
	Haber_CONTACTS   Haber_Which = 1
	Haber_PRESENCE   Haber_Which = 2
	Haber_TEXT       Haber_Which = 3
	Haber_FILE       Haber_Which = 4
	Haber_AV         Haber_Which = 5
	Haber_STORE      Haber_Which = 6
	Haber_LOAD       Haber_Which = 7
	Haber_PAYLOAD    Haber_Which = 8
	Haber_PUBLIC_KEY Haber_Which = 9
)

var Haber_Which_name = map[int32]string{
	0: "LOGIN",
	1: "CONTACTS",
	2: "PRESENCE",
	3: "TEXT",
	4: "FILE",
	5: "AV",
	6: "STORE",
	7: "LOAD",
	8: "PAYLOAD",
	9: "PUBLIC_KEY",
}
var Haber_Which_value = map[string]int32{
	"LOGIN":      0,
	"CONTACTS":   1,
	"PRESENCE":   2,
	"TEXT":       3,
	"FILE":       4,
	"AV":         5,
	"STORE":      6,
	"LOAD":       7,
	"PAYLOAD":    8,
	"PUBLIC_KEY": 9,
}

func (x Haber_Which) String() string {
	return proto.EnumName(Haber_Which_name, int32(x))
}
func (Haber_Which) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type Login struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Login) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Contact struct {
	Id          []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	Online      bool   `protobuf:"varint,3,opt,name=online" json:"online,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Contact) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contact) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Contact) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

type Text struct {
	Body string `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
}

func (m *Text) Reset()                    { *m = Text{} }
func (m *Text) String() string            { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()               {}
func (*Text) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Text) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type File struct {
	Key  string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *File) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Av struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Av) Reset()                    { *m = Av{} }
func (m *Av) String() string            { return proto.CompactTextString(m) }
func (*Av) ProtoMessage()               {}
func (*Av) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Av) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Store struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Store) Reset()                    { *m = Store{} }
func (m *Store) String() string            { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()               {}
func (*Store) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Store) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Store) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Load struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Load) Reset()                    { *m = Load{} }
func (m *Load) String() string            { return proto.CompactTextString(m) }
func (*Load) ProtoMessage()               {}
func (*Load) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Load) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Haber struct {
	Version   uint32      `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	SessionId string      `protobuf:"bytes,2,opt,name=sessionId" json:"sessionId,omitempty"`
	From      []byte      `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To        []byte      `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Which     Haber_Which `protobuf:"varint,5,opt,name=which,enum=Haber_Which" json:"which,omitempty"`
	// One of the following will be filled in
	Login    *Login     `protobuf:"bytes,101,opt,name=login" json:"login,omitempty"`
	Contacts []*Contact `protobuf:"bytes,102,rep,name=contacts" json:"contacts,omitempty"`
	Text     *Text      `protobuf:"bytes,104,opt,name=text" json:"text,omitempty"`
	Av       *Av        `protobuf:"bytes,105,opt,name=av" json:"av,omitempty"`
	File     *File      `protobuf:"bytes,106,opt,name=file" json:"file,omitempty"`
	Store    *Store     `protobuf:"bytes,107,opt,name=store" json:"store,omitempty"`
	Load     *Load      `protobuf:"bytes,108,opt,name=load" json:"load,omitempty"`
	Raw      [][]byte   `protobuf:"bytes,109,rep,name=raw,proto3" json:"raw,omitempty"`
	Payload  []byte     `protobuf:"bytes,110,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Haber) Reset()                    { *m = Haber{} }
func (m *Haber) String() string            { return proto.CompactTextString(m) }
func (*Haber) ProtoMessage()               {}
func (*Haber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Haber) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Haber) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Haber) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Haber) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Haber) GetWhich() Haber_Which {
	if m != nil {
		return m.Which
	}
	return Haber_LOGIN
}

func (m *Haber) GetLogin() *Login {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *Haber) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Haber) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Haber) GetAv() *Av {
	if m != nil {
		return m.Av
	}
	return nil
}

func (m *Haber) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Haber) GetStore() *Store {
	if m != nil {
		return m.Store
	}
	return nil
}

func (m *Haber) GetLoad() *Load {
	if m != nil {
		return m.Load
	}
	return nil
}

func (m *Haber) GetRaw() [][]byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Haber) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Login)(nil), "Login")
	proto.RegisterType((*Contact)(nil), "Contact")
	proto.RegisterType((*Text)(nil), "Text")
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterType((*Av)(nil), "Av")
	proto.RegisterType((*Store)(nil), "Store")
	proto.RegisterType((*Load)(nil), "Load")
	proto.RegisterType((*Haber)(nil), "Haber")
	proto.RegisterEnum("Haber_Which", Haber_Which_name, Haber_Which_value)
}

func init() { proto.RegisterFile("wire.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x53, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0xfd, 0xe5, 0x5f, 0x9b, 0xde, 0xe6, 0x37, 0x45, 0x06, 0x21, 0x33, 0x4d, 0x22, 0x0a, 0x48,
	0xf4, 0x01, 0x05, 0x69, 0x7c, 0x82, 0xac, 0x64, 0x50, 0x11, 0xb5, 0x93, 0x1b, 0xfe, 0x8c, 0x97,
	0xc9, 0x6d, 0xdc, 0xd5, 0x2c, 0x8d, 0xa7, 0xc4, 0x4d, 0x57, 0x89, 0x2f, 0xce, 0x1b, 0xb2, 0x93,
	0x96, 0x21, 0xde, 0xee, 0x39, 0xe7, 0xde, 0xeb, 0xab, 0x73, 0x64, 0x80, 0x1d, 0xaf, 0x58, 0x74,
	0x5f, 0x09, 0x29, 0xc2, 0x97, 0xe0, 0xa4, 0xe2, 0x96, 0x97, 0xe8, 0x14, 0xdc, 0x6d, 0xcd, 0xaa,
	0x92, 0x6e, 0x18, 0x36, 0x02, 0x63, 0x34, 0x20, 0x47, 0x1c, 0xce, 0xa1, 0x3f, 0x16, 0xa5, 0xa4,
	0x4b, 0x89, 0x4e, 0xc0, 0xe4, 0xb9, 0x6e, 0xf0, 0x88, 0xc9, 0x73, 0x14, 0xc0, 0x30, 0xe7, 0xf5,
	0x7d, 0x41, 0xf7, 0x53, 0x35, 0x69, 0xea, 0xc9, 0xc7, 0x14, 0x7a, 0x06, 0x3d, 0x51, 0x16, 0xbc,
	0x64, 0xd8, 0x0a, 0x8c, 0x91, 0x4b, 0x3a, 0x14, 0x9e, 0x82, 0x9d, 0xb1, 0x07, 0x89, 0x10, 0xd8,
	0x0b, 0x91, 0xef, 0xbb, 0x47, 0x75, 0x1d, 0xbe, 0x01, 0xfb, 0x92, 0x17, 0x0c, 0xf9, 0x60, 0xdd,
	0xb1, 0x83, 0xa4, 0x4a, 0xd5, 0x9d, 0x53, 0x49, 0xf5, 0x43, 0x1e, 0xd1, 0x75, 0x88, 0xc1, 0x8c,
	0x9b, 0xa3, 0x62, 0x3c, 0x52, 0xde, 0x82, 0x33, 0x97, 0xa2, 0xfa, 0x6b, 0x91, 0xd7, 0x2e, 0x7a,
	0x0a, 0x4e, 0x43, 0x8b, 0x2d, 0xeb, 0x36, 0xb5, 0x20, 0xc4, 0x60, 0xa7, 0x82, 0xe6, 0xff, 0xf6,
	0x87, 0xbf, 0x2c, 0x70, 0x3e, 0xd2, 0x05, 0xab, 0x10, 0x86, 0x7e, 0xc3, 0xaa, 0x9a, 0x8b, 0x52,
	0xeb, 0xff, 0x93, 0x03, 0x44, 0x67, 0x30, 0xa8, 0x59, 0xad, 0xca, 0x49, 0xde, 0x59, 0xf1, 0x87,
	0x50, 0x07, 0xae, 0x2a, 0xb1, 0xd1, 0x36, 0x78, 0x44, 0xd7, 0xca, 0x4e, 0x29, 0xb0, 0xdd, 0xda,
	0x29, 0x05, 0x0a, 0xc1, 0xd9, 0xad, 0xf9, 0x72, 0x8d, 0x9d, 0xc0, 0x18, 0x9d, 0x9c, 0x7b, 0x91,
	0x7e, 0x32, 0xfa, 0xaa, 0x38, 0xd2, 0x4a, 0xe8, 0x0c, 0x9c, 0x42, 0x45, 0x86, 0x59, 0x60, 0x8c,
	0x86, 0xe7, 0xbd, 0x48, 0x07, 0x48, 0x5a, 0x12, 0xbd, 0x02, 0x77, 0xd9, 0x66, 0x55, 0xe3, 0x55,
	0x60, 0x8d, 0x86, 0xe7, 0x6e, 0xd4, 0x85, 0x47, 0x8e, 0x0a, 0x7a, 0x0e, 0xb6, 0x64, 0x0f, 0x12,
	0xaf, 0xf5, 0x0a, 0x27, 0x52, 0x49, 0x10, 0x4d, 0xa1, 0x27, 0x60, 0xd2, 0x06, 0x73, 0x2d, 0x58,
	0x51, 0xdc, 0x10, 0x93, 0x36, 0xaa, 0x7f, 0xc5, 0x0b, 0x86, 0x7f, 0x74, 0xfd, 0x2a, 0x1d, 0xa2,
	0x29, 0x75, 0x4e, 0xad, 0x3c, 0xc6, 0x77, 0xdd, 0x39, 0xda, 0x71, 0xd2, 0x92, 0x6a, 0xb0, 0x10,
	0x34, 0xc7, 0x45, 0x37, 0xa8, 0xdc, 0x25, 0x9a, 0x52, 0x1e, 0x57, 0x74, 0x87, 0x37, 0x81, 0xa5,
	0x3c, 0xae, 0xe8, 0x4e, 0x39, 0x7b, 0x4f, 0xf7, 0xba, 0xbf, 0xd4, 0x96, 0x1c, 0x60, 0xf8, 0x13,
	0x1c, 0xed, 0x01, 0x1a, 0x80, 0x93, 0xce, 0x3e, 0x4c, 0xa6, 0xfe, 0x7f, 0xc8, 0x03, 0x77, 0x3c,
	0x9b, 0x66, 0xf1, 0x38, 0x9b, 0xfb, 0x86, 0x42, 0x57, 0x24, 0x99, 0x27, 0xd3, 0x71, 0xe2, 0x9b,
	0xc8, 0x05, 0x3b, 0x4b, 0xbe, 0x65, 0xbe, 0xa5, 0xaa, 0xcb, 0x49, 0x9a, 0xf8, 0x36, 0xea, 0x81,
	0x19, 0x7f, 0xf1, 0x1d, 0xb5, 0x62, 0x9e, 0xcd, 0x48, 0xe2, 0xf7, 0x94, 0x98, 0xce, 0xe2, 0xf7,
	0x7e, 0x1f, 0x0d, 0xa1, 0x7f, 0x15, 0x5f, 0x6b, 0xe0, 0xa2, 0x13, 0x80, 0xab, 0xcf, 0x17, 0xe9,
	0x64, 0x7c, 0xf3, 0x29, 0xb9, 0xf6, 0x07, 0x17, 0xaf, 0xe1, 0x45, 0xc5, 0xf2, 0x48, 0xb2, 0x22,
	0x5a, 0xae, 0xa9, 0x8c, 0x6e, 0x59, 0xc9, 0x2a, 0x2a, 0x59, 0x7e, 0xa3, 0x3f, 0xd1, 0x62, 0xbb,
	0xfa, 0x6e, 0x6f, 0x28, 0x2f, 0x17, 0x3d, 0x8d, 0xdf, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xca, 0x56, 0x34, 0x62, 0x03, 0x00, 0x00,
}
