// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: wire.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class File extends AndroidMessage<File, File.Builder> {
  public static final ProtoAdapter<File> ADAPTER = new ProtoAdapter_File();

  public static final Parcelable.Creator<File> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_KEY = "";

  public static final ByteString DEFAULT_DATA = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String key;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString data;

  public File(String key, ByteString data) {
    this(key, data, ByteString.EMPTY);
  }

  public File(String key, ByteString data, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.key = key;
    this.data = data;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.key = key;
    builder.data = data;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof File)) return false;
    File o = (File) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(key, o.key)
        && Internal.equals(data, o.data);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (key != null ? key.hashCode() : 0);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (key != null) builder.append(", key=").append(key);
    if (data != null) builder.append(", data=").append(data);
    return builder.replace(0, 2, "File{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<File, Builder> {
    public String key;

    public ByteString data;

    public Builder() {
    }

    public Builder key(String key) {
      this.key = key;
      return this;
    }

    public Builder data(ByteString data) {
      this.data = data;
      return this;
    }

    @Override
    public File build() {
      return new File(key, data, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_File extends ProtoAdapter<File> {
    public ProtoAdapter_File() {
      super(FieldEncoding.LENGTH_DELIMITED, File.class);
    }

    @Override
    public int encodedSize(File value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.key)
          + ProtoAdapter.BYTES.encodedSizeWithTag(2, value.data)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, File value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.key);
      ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.data);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public File decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.key(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.data(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public File redact(File value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
