// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: wire.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Login extends AndroidMessage<Login, Login.Builder> {
  public static final ProtoAdapter<Login> ADAPTER = new ProtoAdapter_Login();

  public static final Parcelable.Creator<Login> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_USERNAME = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String username;

  public Login(String username) {
    this(username, ByteString.EMPTY);
  }

  public Login(String username, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.username = username;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.username = username;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Login)) return false;
    Login o = (Login) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(username, o.username);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (username != null ? username.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (username != null) builder.append(", username=").append(username);
    return builder.replace(0, 2, "Login{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Login, Builder> {
    public String username;

    public Builder() {
    }

    public Builder username(String username) {
      this.username = username;
      return this;
    }

    @Override
    public Login build() {
      return new Login(username, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Login extends ProtoAdapter<Login> {
    public ProtoAdapter_Login() {
      super(FieldEncoding.LENGTH_DELIMITED, Login.class);
    }

    @Override
    public int encodedSize(Login value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.username)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Login value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.username);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Login decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.username(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Login redact(Login value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
