// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: wire.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Store extends AndroidMessage<Store, Store.Builder> {
  public static final ProtoAdapter<Store> ADAPTER = new ProtoAdapter_Store();

  public static final Parcelable.Creator<Store> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_KEY = ByteString.EMPTY;

  public static final ByteString DEFAULT_VALUE = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString key;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString value;

  public Store(ByteString key, ByteString value) {
    this(key, value, ByteString.EMPTY);
  }

  public Store(ByteString key, ByteString value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.key = key;
    this.value = value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.key = key;
    builder.value = value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Store)) return false;
    Store o = (Store) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(key, o.key)
        && Internal.equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (key != null ? key.hashCode() : 0);
      result = result * 37 + (value != null ? value.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (key != null) builder.append(", key=").append(key);
    if (value != null) builder.append(", value=").append(value);
    return builder.replace(0, 2, "Store{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Store, Builder> {
    public ByteString key;

    public ByteString value;

    public Builder() {
    }

    public Builder key(ByteString key) {
      this.key = key;
      return this;
    }

    public Builder value(ByteString value) {
      this.value = value;
      return this;
    }

    @Override
    public Store build() {
      return new Store(key, value, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Store extends ProtoAdapter<Store> {
    public ProtoAdapter_Store() {
      super(FieldEncoding.LENGTH_DELIMITED, Store.class);
    }

    @Override
    public int encodedSize(Store value) {
      return ProtoAdapter.BYTES.encodedSizeWithTag(1, value.key)
          + ProtoAdapter.BYTES.encodedSizeWithTag(2, value.value)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Store value) throws IOException {
      ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.key);
      ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.value);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Store decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.key(ProtoAdapter.BYTES.decode(reader)); break;
          case 2: builder.value(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Store redact(Store value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
