// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: voip.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class TextStorage extends AndroidMessage<TextStorage, TextStorage.Builder> {
  public static final ProtoAdapter<TextStorage> ADAPTER = new ProtoAdapter_TextStorage();

  public static final Parcelable.Creator<TextStorage> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_FROM = "";

  public static final String DEFAULT_TO = "";

  public static final ByteString DEFAULT_BODY = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String from;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String to;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString body;

  public TextStorage(String from, String to, ByteString body) {
    this(from, to, body, ByteString.EMPTY);
  }

  public TextStorage(String from, String to, ByteString body, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.from = from;
    this.to = to;
    this.body = body;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.from = from;
    builder.to = to;
    builder.body = body;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TextStorage)) return false;
    TextStorage o = (TextStorage) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(from, o.from)
        && Internal.equals(to, o.to)
        && Internal.equals(body, o.body);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (from != null ? from.hashCode() : 0);
      result = result * 37 + (to != null ? to.hashCode() : 0);
      result = result * 37 + (body != null ? body.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (from != null) builder.append(", from=").append(from);
    if (to != null) builder.append(", to=").append(to);
    if (body != null) builder.append(", body=").append(body);
    return builder.replace(0, 2, "TextStorage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TextStorage, Builder> {
    public String from;

    public String to;

    public ByteString body;

    public Builder() {
    }

    public Builder from(String from) {
      this.from = from;
      return this;
    }

    public Builder to(String to) {
      this.to = to;
      return this;
    }

    public Builder body(ByteString body) {
      this.body = body;
      return this;
    }

    @Override
    public TextStorage build() {
      return new TextStorage(from, to, body, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TextStorage extends ProtoAdapter<TextStorage> {
    public ProtoAdapter_TextStorage() {
      super(FieldEncoding.LENGTH_DELIMITED, TextStorage.class);
    }

    @Override
    public int encodedSize(TextStorage value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.from)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.to)
          + ProtoAdapter.BYTES.encodedSizeWithTag(3, value.body)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, TextStorage value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.from);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.to);
      ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.body);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TextStorage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.from(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.to(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.body(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public TextStorage redact(TextStorage value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
