# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
platform :osx, '10.12'

target 'Chat' do
  use_frameworks!
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift3'
  pod 'ProtocolBuffers-Swift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.12'
    end
  end
end
