platform :osx, '10.12'

target 'Chat' do
  use_frameworks!
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift3', :inhibit_warnings => true
  pod 'ProtocolBuffers-Swift', :inhibit_warnings => true
  pod 'themis', :podspec => 'https://raw.githubusercontent.com/cossacklabs/themis/master/themis.podspec', :inhibit_warnings => true
end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.12'
    end
  end
end
