# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Chat' do
  use_frameworks!
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift3'
  pod 'ProtocolBuffers-Swift'
  pod 'RNCryptor', '~> 5.0'
  pod 'SignalProtocolObjC'
end
